server/config/routes.rb
Rails.application.routes.draw do
  resources :devices
  resources :media_items
  resources :scraps
  resources :offers
  resources :news
  devise_for :users

  root to: 'users#index'

  post 'channels/:id/scrap' => 'channels#create_scrap'
  post 'channels/:id/play' => 'channels#play'
  resources :channels

  put 'establishments/select_channel/:channel_id' => 'establishments#select_channel'
  resources :establishments

  post 'users/facebook_login' => 'users#facebook_login'
  resources :users

end

server/app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :channel
end

server/app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]

  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(offer_params)

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Offer was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer, notice: 'Offer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_to offers_url, notice: 'Offer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:title, :price, :channel_id)
    end
end

server/app/helpers/offers_helper.rb
module OffersHelper
end

server/app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :channel_id %><br>
    <%= f.text_field :channel_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

server/app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Offers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Channel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offers.each do |offer| %>
      <tr>
        <td><%= offer.title %></td>
        <td><%= offer.price %></td>
        <td><%= offer.channel %></td>
        <td><%= link_to 'Show', offer %></td>
        <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
        <td><%= link_to 'Destroy', offer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offer', new_offer_path %>

server/app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

server/app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @offer.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @offer.price %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @offer.channel %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>