server/config/routes.rb
Rails.application.routes.draw do
  resources :devices
  resources :media_items
  resources :scraps
  resources :offers
  resources :news
  devise_for :users

  root to: 'users#index'

  post 'channels/:id/scrap' => 'channels#create_scrap'
  post 'channels/:id/play' => 'channels#play'
  resources :channels

  put 'establishments/select_channel/:channel_id' => 'establishments#select_channel'
  resources :establishments

  post 'users/facebook_login' => 'users#facebook_login'
  resources :users

end

server/app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :user
end

server/app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:user_id, :platform, :uuid)
    end
end

server/app/helpers/devices_helper.rb
module DevicesHelper
end

server/app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :platform %><br>
    <%= f.text_field :platform %>
  </div>
  <div class="field">
    <%= f.label :uuid %><br>
    <%= f.text_field :uuid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

server/app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Devices</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Platform</th>
      <th>Uuid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.user %></td>
        <td><%= device.platform %></td>
        <td><%= device.uuid %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

server/app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

server/app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @device.user %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @device.platform %>
</p>

<p>
  <strong>Uuid:</strong>
  <%= @device.uuid %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>