server/config/routes.rb
Rails.application.routes.draw do
  resources :devices
  resources :media_items
  resources :scraps
  resources :offers
  resources :news
  devise_for :users

  root to: 'users#index'

  post 'channels/:id/scrap' => 'channels#create_scrap'
  post 'channels/:id/play' => 'channels#play'
  resources :channels

  put 'establishments/select_channel/:channel_id' => 'establishments#select_channel'
  resources :establishments

  post 'users/facebook_login' => 'users#facebook_login'
  resources :users

end

server/app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :channel
end

server/app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :content, :channel_id)
    end
end

server/app/helpers/news_helper.rb
module NewsHelper
end

server/app/views/news/_form.html.erb
<%= form_for(@news) do |f| %>
  <% if @news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% @news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :channel_id %><br>
    <%= f.text_field :channel_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form' %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

server/app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing News</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Channel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.content %></td>
        <td><%= news.channel %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

server/app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path %>

server/app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @news.content %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @news.channel %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>